move find gpu to top of the test

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -22,6 +22,14 @@ jobs:
       image: pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel
 
     steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Compile
+        run: |
+          pip install -U pytest ninja parameterized protobuf
+          pip install -v --no-build-isolation .
+
       - name: Find suitable GPU
         run: |
           suitable_gpu=$(nvidia-smi -L | grep "RTX 4090" | awk -F': ' '{print $1}' | sed 's/GPU //g' | while read gpu_id
@@ -34,18 +42,13 @@ jobs:
               break
             fi
           done)
-          echo "CUDA_VISIBLE_DEVICES=$suitable_gpu" >> $GITHUB_ENV
-
-      - name: Display Environment Variable
-        run: echo "CUDA_VISIBLE_DEVICES set to ${{ env.CUDA_VISIBLE_DEVICES }}"
-
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Compile
-        run: |
-          pip install -U pytest ninja parameterized protobuf
-          pip install -v --no-build-isolation .
+          if [ -z "$suitable_gpu" ]; then
+            echo "No suitable GPU found. Exiting with error."
+            exit 1
+          else
+            echo "CUDA_VISIBLE_DEVICES=$suitable_gpu" >> $GITHUB_ENV
+          echo "CUDA_VISIBLE_DEVICES set to ${{ env.CUDA_VISIBLE_DEVICES }}"
+          fi
 
       - name: test_lm_head.py
         if: ${{ !github.event.inputs.test_names || contains(github.event.inputs.test_names, 'test_lm_head') }}
