[CI] Check server status by gpu selector (#241)
* check vm by gpu selector

* update scripts

* update format

* Update run_tests.yml

* move install req to a step

* if runner name has intel, no need curl

* set if to always

* add - check-vm

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -34,48 +34,42 @@ jobs:
         id: get_ip
         shell: bash
         run: |
-          json=$(curl -sL \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: Bearer ${{ secrets.RUNNER_TOKEN }}" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            https://api.github.com/repos/${{ github.repository }}/actions/runners)
-
-          result=$(python3 - <<EOF
-          import json
-          runners = json.loads('''$json''')['runners']
-          result = all(
-              (runner['status'] == 'offline' or runner['busy'])
-              for runner in runners
-              if any(label['name'] == 'self-hosted' for label in runner['labels']) and
-                 any(label['name'] == 'X64' for label in runner['labels'])
-          )
-          print(result)
-          EOF
-          )
-
-          if [ "$result" == "True" ]; then
-            tag="amd"
-          elif [ "$result" == "False" ]; then
-            tag="intel"
+          if [[ "${{ runner.name }}" == *"intel"* ]]; then
+            response=0
           else
-            echo "Error: Unexpected result - $result"
+            response=$(curl --silent --fail http://$INTEL_SERVER/gpu/runner/status/available)
+            if [[ $? -ne 0 ]]; then
+              response=$(curl --silent --fail http://${AMD_SERVER}/gpu/runner/status/available)
+            fi
+          fi
+
+          if [ "$response" == "0" ]; then
+            tag="intel"
+          elif [ "$response" == "-1" ]; then
+            tag="amd"
+          else
+            echo "Error: Unexpected result - $response"
             exit 1
           fi
 
           echo "Runner tag: $tag"
 
           if [ "$tag" == "intel" ]; then
-            if curl -s --head --request GET http://${INTEL_SERVER} | grep "200 OK" > /dev/null; then
-              echo "Intel server is online."
+            response=$(curl -s --head --request GET http://${INTEL_SERVER}/gpu/status)
+            #  echo "Intel server response: $response"
+            if echo "$response" | grep "200 OK" > /dev/null; then
+              echo "Intel server is online. set ip to $ip"
               ip=${INTEL_SERVER}
             else
               echo "Intel server is offline."
               exit 1
             fi
           elif [ "$tag" == "amd" ]; then
-            if curl -s --head --request GET http://${AMD_SERVER} | grep "200 OK" > /dev/null; then
-              echo "AMD server is online."
+            response=$(curl -s --head --request GET http://${AMD_SERVER}/gpu/status)
+            #  echo "AMD server response: '$response'"
+            if echo "$response" | grep "200 OK" > /dev/null; then
               ip=${AMD_SERVER}
+              echo "AMD server is online. set ip to $ip"
             else
               echo "AMD server is offline."
               exit 1
@@ -86,8 +80,9 @@ jobs:
           echo "tag=$tag" >> "$GITHUB_OUTPUT"
 
           echo "tag: $tag, ip: $ip"
+
   build-intel:
-    runs-on: self-hosted
+    runs-on: [self-hosted, intel]
     needs: check-vm
     if: needs.check-vm.outputs.tag == 'intel'
     container:
@@ -99,6 +94,10 @@ jobs:
           repository: ${{ github.event.inputs.repo }}
           ref: ${{ github.event.inputs.ref }}
 
+      - name: Install requirements
+        shell: bash
+        run: pip install -r requirements.txt
+
       - name: Compile
         shell: bash
         run: python setup.py bdist_wheel
@@ -108,18 +107,24 @@ jobs:
         with:
           name: dist
           path: dist
+
   build-amd:
-    runs-on: self-hosted
+    runs-on: [self-hosted, amd]
     needs: check-vm
     if: needs.check-vm.outputs.tag == 'amd'
     container:
       image:  ${{ needs.check-vm.outputs.ip }}:5000/modelcloud/gptqmodel:github-ci-v2
+
     steps:
       - name: Checkout Codes
         uses: actions/checkout@v4
         with:
           repository: ${{ github.event.inputs.repo }}
           ref: ${{ github.event.inputs.ref }}
+
+      - name: Install requirements
+        shell: bash
+        run: pip install -r requirements.txt
 
       - name: Compile
         shell: bash
@@ -136,6 +141,7 @@ jobs:
     outputs:
       cpu-files: ${{ steps.files.outputs.cpu-files }}
       gpu-files: ${{ steps.files.outputs.gpu-files }}
+
     steps:
       - name: Checkout Codes
         uses: actions/checkout@v4
@@ -175,8 +181,9 @@ jobs:
       - build-intel
       - build-amd
       - list-test-files
+      - check-vm
     runs-on: self-hosted
-    if: success() && (needs.build-intel.result == 'success' || needs.build-amd.result == 'success')
+    if: always() && (needs.build-intel.result == 'success' || needs.build-amd.result == 'success')
     container:
       image: ${{ needs.check-vm.outputs.ip }}:5000/modelcloud/gptqmodel:github-ci-v2
     strategy:
@@ -214,8 +221,7 @@ jobs:
       - name: Check platform
         shell: bash
         run: |
-          vendor=$(lscpu | grep 'Vendor ID')
-          if [[ $vendor == *"Intel"* ]]; then
+          if [[ "${{ runner.name }}" == *"intel"* ]]; then
             ip=${INTEL_SERVER}
           else
             ip=${AMD_SERVER}
@@ -256,7 +262,7 @@ jobs:
       - list-test-files
       - check-vm
     runs-on: self-hosted
-    if: success() && (needs.build-intel.result == 'success' || needs.build-amd.result == 'success')
+    if: always() && (needs.build-intel.result == 'success' || needs.build-amd.result == 'success')
     container:
       image: ${{ needs.check-vm.outputs.ip }}:5000/modelcloud/gptqmodel:github-ci-v2
     strategy:
