handle error

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -54,9 +54,12 @@ jobs:
           )
 
           if [ "$result" == "True" ]; then
-            tag=intel
+            tag="intel"
+          elif [ "$result" == "False" ]; then
+            tag="amd"
           else
-            tag=amd
+            echo "Error: Unexpected result - $result"
+            exit 1
           fi
 
           if curl -s --head --request GET http://${INTEL_SERVER} | grep "200 OK" > /dev/null; then
