Update run_tests.yml

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -17,9 +17,7 @@ jobs:
         - /tmp:/data:rw
     steps:
       - name: Compile
-        run: |
-          mkdir dist || true
-          echo 1234 > dist/1234.whl
+        run: python setup.py bdist_wheel
 
       - name: show dist folder
         run: ls -ahl dist
@@ -45,7 +43,7 @@ jobs:
     steps:
       - name: Print whl from shared dir
         run: |
-          ls -ahl /data
+          ls -ahl /data || true
 
       - name: Print whl from shared dir
         run: |
@@ -53,11 +51,31 @@ jobs:
 
       - name: Install whl from shared dir
         run: |
-          cat /data/${{ github.run_id }}/*.whl
+          pip install /data/${{ github.run_id }}/*.whl
+
+      - name: Find suitable GPU
+        run: |
+         suitable_gpu=$(nvidia-smi -L | grep "RTX 4090" | awk -F': ' '{print $1}' | sed 's/GPU //g' | while read gpu_id
+          do
+            mem_total=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits -i $gpu_id)
+            mem_used=$(nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits -i $gpu_id)
+            mem_used_pct=$((100 * mem_used / mem_total))
+            if [ $mem_used_pct -lt 2 ]; then # 2 -> 98% free
+              echo $gpu_id
+              break
+            fi
+          done)
+          if [ -z "$suitable_gpu" ]; then
+            echo "No suitable GPU found. Exiting with error."
+            exit 1
+          else
+            echo "CUDA_VISIBLE_DEVICES=$suitable_gpu" >> $GITHUB_ENV
+            echo "CUDA_VISIBLE_DEVICES set to $suitable_gpu"
+          fi
 
       - name: Run tests group 1
         if: matrix.test-group == 'gpu_group1'
-        run: cat /data/${{ github.run_id }}/*.whl
+        run: pytest tests/test_perplexity.py
 
       - name: Run tests group 2
         if: matrix.test-group == 'gpu_group2'
@@ -76,7 +94,17 @@ jobs:
               echo -e "========================================\n\n\n"
           }
           
-          cat /data/${{ github.run_id }}/*.whl
+          run_test test_lm_head.py
+          run_test test_q4_exallama.py
+          run_test test_q4_exallama_v2.py
+          run_test test_q4_marlin.py
+          run_test test_q4_triton.py
+          run_test test_repacking.py
+          run_test test_serialization.py
+          run_test test_sharded.py
+          run_test test_triton.py
+          run_test test_quant_formats.py
+          run_test test_q4_cuda.py
           
           if [ ${#failed_tests[@]} -ne 0 ]; then
               echo -e "\033[1;31mTests failed:\033[0m"
