[CI] save log to disk & fix deps installation (#2418)
* [CI] save logs to disk

* [CI] rename api

* [CI] install swig

* [CI] list logs dir

* [CI] move install deps to top

* [CI] isntall deps 1 by 1

* [CI] echo url

* [CI] fix install torch

* [CI] no error for releasing GPU

diff --git a/.github/workflows/unit_tests.yml b/.github/workflows/unit_tests.yml
--- a/.github/workflows/unit_tests.yml
+++ b/.github/workflows/unit_tests.yml
@@ -406,6 +406,7 @@ jobs:
 
           echo "setting env... cuda=${{ needs.check-vm.outputs.cuda_version }} torch=${{ env.TORCH_VERSION }} python=${{ env.PYTHON_VERSION }}"
           bash /opt/env/init_compiler_no_env.sh ${{ needs.check-vm.outputs.cuda_version }} ${{ env.TORCH_VERSION }} ${{ env.PYTHON_VERSION }}
+          python .github/scripts/install_deps.py ${{ matrix.test_script }}
 
       - name: Print uv env
         run: |
@@ -506,7 +507,7 @@ jobs:
         run: |
           uv pip uninstall gptqmodel
           # make sure torch & torchvision are corresponded
-          uv pip install -U torchvision torchaudio torch==${{ env.TORCH_VERSION }} --torch-backend=cu${{ needs.check-vm.outputs.cuda_version }}
+          /opt/env/install_torch.sh ${{ needs.check-vm.outputs.cuda_version }} ${{ env.TORCH_VERSION }}
           uv pip install -r requirements.txt
 
           if [[ "${{ matrix.test_script }}" == *xpu* ]]; then
@@ -525,9 +526,8 @@ jobs:
             uv pip install . --no-build-isolation
           fi
 
-          python .github/scripts/install_deps.py ${{ matrix.test_script }}
           # deps may reinstalled torch
-          uv pip install -U torchvision torchaudio torch==${{ env.TORCH_VERSION }} --torch-backend=cu${{ needs.check-vm.outputs.cuda_version }}
+          /opt/env/install_torch.sh ${{ needs.check-vm.outputs.cuda_version }} ${{ env.TORCH_VERSION }}
 
       - name: Find suitable GPU
         if: ${{ !contains(matrix.test_script, 'ipex') && !contains(matrix.test_script, 'xpu') && !cancelled() }}
@@ -632,9 +632,10 @@ jobs:
           fi
           
           start_monitor() {
-            echo "start to keep alive..."
+            keep_alive_url="http://$XEON5/gpu/keepalive?runid=${{ github.run_id }}&test=${{ matrix.test_script }}&runner=${RUNNER_NAME}&timestamp=$(date +%s)&exclusive=${{ github.event.inputs['exclusive-gpu'] }}&gpu=${CUDA_VISIBLE_DEVICES}"
+            echo "start to keep alive... ${keep_alive_url}"
             while true; do
-              resp=$(curl -fsSL "http://$XEON5/gpu/keepalive?runid=${{ github.run_id }}&test=${{ matrix.test_script }}&runner=${RUNNER_NAME}&timestamp=$(date +%s)&exclusive=${{ github.event.inputs['exclusive-gpu'] }}&gpu=${CUDA_VISIBLE_DEVICES}" 2>/dev/null || echo "")
+              resp=$(curl -fsSL $keep_alive_url 2>/dev/null || echo "")
           
               if [ "$(echo "$resp" | tr -d '[:space:]')" = "-1" ]; then
                 echo "Server returned -1, terminating job..."
@@ -658,12 +659,19 @@ jobs:
           }
           trap cleanup EXIT
           
+          log_dir=/opt/dist/${{ needs.check-vm.outputs.run_id }}/logs
+          [ -d $log_dir ] || mkdir -p $log_dir
+          log_file=$log_dir/${{ matrix.test_script }}.log
+          
           start_time=$(date +%s)
-          pytest --durations=0 tests/${{ matrix.test_script }}.py || { echo "ERROR=1" >> $GITHUB_ENV; exit 1; }
+          pytest --durations=0 tests/${{ matrix.test_script }}.py 2>&1 | tee $log_file
+          test ${PIPESTATUS[0]} -eq 0 || { echo "ERROR=1" >> $GITHUB_ENV; exit 1; }
           execution_time=$(( $(date +%s) - start_time ))
           echo "$((execution_time / 60))m $((execution_time % 60))s"
           
-          curl "http://$XEON5/gpu/log_test_vram?runid=${{ github.run_id }}&gpu=${{ env.CUDA_VISIBLE_DEVICES }}&range=$execution_time&unit=second&test=${{ matrix.test_script }}"
+          ls -ahl $log_dir || true
+
+          curl "http://$XEON5/gpu/logVram?runid=${{ github.run_id }}&gpu=${{ env.CUDA_VISIBLE_DEVICES }}&range=$execution_time&unit=second&test=${{ matrix.test_script }}"
 
       - name: Release GPU
         if: always() && !contains(matrix.test_script, 'ipex') && !contains(matrix.test_script, 'xpu')
@@ -675,7 +683,7 @@ jobs:
           echo "response: $resp"
           if [ "$resp" != "${{ env.CUDA_VISIBLE_DEVICES }}" ]; then
             echo "Error: response ($resp) != expected (${{ env.CUDA_VISIBLE_DEVICES }})"
-            exit 1
+            exit 0
           fi
 
       - name: Clean cache
