[CI] fix indentation (#632)
* [CI] fix indentation

* fix indentation

diff --git a/.github/workflows/unit_tests.yml b/.github/workflows/unit_tests.yml
--- a/.github/workflows/unit_tests.yml
+++ b/.github/workflows/unit_tests.yml
@@ -386,44 +386,44 @@ jobs:
           echo "== torch =="
           pip show torch
 
-          - name: Download wheel
-            continue-on-error: true
-            run: |
-              file_name=$(curl -s  -F "runid=${{ needs.check-vm.outputs.run_id }}" -F "repo=${{ env.repo }}" -F "ref=${{ env.ref }}" -F "fuzz=1" "http://${{ needs.check-vm.outputs.ip }}/gpu/whl/download")
+      - name: Download wheel
+        continue-on-error: true
+        run: |
+          file_name=$(curl -s  -F "runid=${{ needs.check-vm.outputs.run_id }}" -F "repo=${{ env.repo }}" -F "ref=${{ env.ref }}" -F "fuzz=1" "http://${{ needs.check-vm.outputs.ip }}/gpu/whl/download")
 
-              if echo "$file_name" | grep -q "gptqmodel"; then
-                  mkdir dist || true
-                  cd dist
-                  curl -s -O  http://${{ needs.check-vm.outputs.ip }}/whl/${{ env.repo }}/${{ needs.check-vm.outputs.run_id }}/$file_name
-                  ls -ahl .
-                  sha256=$(sha256sum $file_name)
-                  echo "sha256=$sha256"
-                  echo "DOWNLOADED=1" >> $GITHUB_ENV
-              fi
+          if echo "$file_name" | grep -q "gptqmodel"; then
+              mkdir dist || true
+              cd dist
+              curl -s -O  http://${{ needs.check-vm.outputs.ip }}/whl/${{ env.repo }}/${{ needs.check-vm.outputs.run_id }}/$file_name
+              ls -ahl .
+              sha256=$(sha256sum $file_name)
+              echo "sha256=$sha256"
+              echo "DOWNLOADED=1" >> $GITHUB_ENV
+          fi
 
-          - name: Download artifact
-            if: env.DOWNLOADED == '' && !cancelled()
-            uses: actions/download-artifact@v4
-            with:
-              name: dist
-              path: dist
-              run-id: ${{ needs.check-vm.outputs.run_id }}
+      - name: Download artifact
+        if: env.DOWNLOADED == '' && !cancelled()
+        uses: actions/download-artifact@v4
+        with:
+          name: dist
+          path: dist
+          run-id: ${{ needs.check-vm.outputs.run_id }}
 
-          - name: Install wheel
-            run: |
-              uv pip install auto_round optimum bitblas==0.0.1.dev13 parameterized uvicorn -i http://${{ needs.check-vm.outputs.ip }}/simple/ --trusted-host ${{ needs.check-vm.outputs.ip }}
-              uv pip install dist/*.whl
-              bash -c "$(curl -L http://$ZEN4_SERVER/scripts/compiler/init_env.sh)" @ 12.4 2.4.1 3.11
-              uv pip install transformers==4.38.2 numpy==1.26.4 -U -i http://${{ needs.check-vm.outputs.ip }}/simple/ --trusted-host ${{ needs.check-vm.outputs.ip }}
+      - name: Install wheel
+        run: |
+          uv pip install auto_round optimum bitblas==0.0.1.dev13 parameterized uvicorn -i http://${{ needs.check-vm.outputs.ip }}/simple/ --trusted-host ${{ needs.check-vm.outputs.ip }}
+          uv pip install dist/*.whl
+          bash -c "$(curl -L http://$ZEN4_SERVER/scripts/compiler/init_env.sh)" @ 12.4 2.4.1 3.11
+          uv pip install transformers==4.38.2 numpy==1.26.4 -U -i http://${{ needs.check-vm.outputs.ip }}/simple/ --trusted-host ${{ needs.check-vm.outputs.ip }}
 
-          - name: Run tests
-            timeout-minutes: ${{ env.BITBLAS == '1' && 120 || 60 }}
-            if: ${{ (!github.event.inputs.test_names || contains(github.event.inputs.test_names, matrix.test_script)) && !cancelled() }}
-            run: pytest --durations=0 tests/${{ matrix.test_script }}.py || { echo "ERROR=1" >> $GITHUB_ENV; exit 1; }
+      - name: Run tests
+        timeout-minutes: ${{ env.BITBLAS == '1' && 120 || 60 }}
+        if: ${{ (!github.event.inputs.test_names || contains(github.event.inputs.test_names, matrix.test_script)) && !cancelled() }}
+        run: pytest --durations=0 tests/${{ matrix.test_script }}.py || { echo "ERROR=1" >> $GITHUB_ENV; exit 1; }
 
-          - name: Release GPU
-            if: always()
-            run: curl -X GET "http://${{ env.GPU_IP }}/gpu/release?id=${{ github.run_id }}&gpu=${{ env.CUDA_VISIBLE_DEVICES }}&timestamp=${{ env.STEP_TIMESTAMP }}"
+      - name: Release GPU
+        if: always()
+        run: curl -X GET "http://${{ env.GPU_IP }}/gpu/release?id=${{ github.run_id }}&gpu=${{ env.CUDA_VISIBLE_DEVICES }}&timestamp=${{ env.STEP_TIMESTAMP }}"
 
   torch2_5:
     needs:
