[FIX] add transformers_diff job (#631)
* add transformers_diff job

* remove subprocess

diff --git a/.github/workflows/unit_tests.yml b/.github/workflows/unit_tests.yml
--- a/.github/workflows/unit_tests.yml
+++ b/.github/workflows/unit_tests.yml
@@ -38,6 +38,7 @@ env:
   CUDA_VISIBLE_DEVICES: 0
   MAX_JOBS: 4
   ZEN4_SERVER: 10.0.14.247
+  TRANSFORMERS_DIFF_TESTS: "models/test_internlm,models/test_internlm2_5,models/test_xverse"
   TORCH_2_5_TESTS: "test_q4_ipex.py,test_save_loaded_quantized_model,test_quant_formats"
   IGNORED_TEST_FILES: "test_tgi.py,test_gptneox.py,models/test_mixtral"
   GPTQMODEL_FORCE_BUILD: 1
@@ -92,6 +93,7 @@ jobs:
     outputs:
       torch-2-5-files: ${{ steps.files.outputs.torch-2-5-files }}
       gpu-files: ${{ steps.files.outputs.gpu-files }}
+      transformers-files: ${{ steps.files.outputs.transformers-files }}
 
     steps:
       - name: Checkout Codes
@@ -119,13 +121,15 @@ jobs:
           cpu_file_list = [f.strip().removesuffix('.py') for f in '${TORCH_2_5_TESTS}'.split(',') if f.strip()]
           test_files_list = [f.strip().removesuffix('.py') for f in '${{ github.event.inputs.test_names }}'.split(',') if f.strip()]
           cpu_test_files = [f for f in cpu_file_list if not test_files_list or f in test_files_list]
+          transformers_diff_list = [f.strip().removesuffix('.py') for f in '${TRANSFORMERS_DIFF_TESTS}'.split(',') if f.strip()]
+          transformers_test_files = [f for f in transformers_diff_list if not test_files_list or f in test_files_list]
 
           all_tests = [f.removesuffix('.py') for f in os.listdir('tests/') if f.startswith('test_') and f.endswith('.py') and f.strip().removesuffix('.py') not in '${IGNORED_TEST_FILES}']
 
           all_tests_models = ['models/'+f.removesuffix('.py') for f in os.listdir('tests/models') if f.startswith('test_') and f.endswith('.py') and f.strip().removesuffix('.py') not in '${IGNORED_TEST_FILES}']
           all_tests = [item for item in all_tests+all_tests_models if item.strip().removesuffix('.py') not in '${TORCH_2_5_TESTS}']
 
-          gpu_test_files = [f for f in all_tests if f not in cpu_file_list and (not test_files_list or f in test_files_list)]
+          gpu_test_files = [f for f in all_tests if f not in cpu_file_list and (not test_files_list or f in test_files_list) and f not in transformers_diff_list]
 
           print(f'{json.dumps(cpu_test_files)}|{json.dumps(gpu_test_files)}')
           "
@@ -134,10 +138,12 @@ jobs:
           IFS='|' read -r cpu_test_files gpu_test_files <<< "$test_files"
           echo "torch-2-5-files=$cpu_test_files" >> "$GITHUB_OUTPUT"
           echo "gpu-files=$gpu_test_files" >> "$GITHUB_OUTPUT"
+          echo "transformers-files=$transformers_test_files" >> "$GITHUB_OUTPUT"
 
           echo "Test files: $test_files"
           echo "CPU Test files: $cpu_test_files"
           echo "GPU Test files: $gpu_test_files"
+          echo "Transformers Test files: $transformers_test_files"
           echo "Ignored Test files: $IGNORED_TEST_FILES"
 
   build-zen4:
@@ -336,6 +342,88 @@ jobs:
       - name: Release GPU
         if: always()
         run: curl -X GET "http://${{ env.GPU_IP }}/gpu/release?id=${{ github.run_id }}&gpu=${{ env.CUDA_VISIBLE_DEVICES }}&timestamp=${{ env.STEP_TIMESTAMP }}"
+
+  transformers_diff:
+    needs:
+      - build-zen4
+      - list-test-files
+      - check-vm
+    runs-on: self-hosted
+    if: always() && !cancelled() && (needs.build-zen4.result == 'success' || github.event.inputs.artifact_id != '')
+    container:
+      image: ${{ needs.check-vm.outputs.ip }}:5000/modelcloud/gptqmodel:github-ci-v2-torch2.4.1
+      volumes:
+        - /home/ci/models:/monster/data/model
+    strategy:
+      fail-fast: false
+      max-parallel: ${{ fromJson(needs.check-vm.outputs.max-parallel).size || 6 }}
+      matrix:
+        test_script: ${{ fromJSON(needs.list-test-files.outputs.transformers-files) }}
+    steps:
+      - name: Checkout Codes
+        uses: actions/checkout@v4
+        with:
+          repository: ${{ github.event.inputs.repo }}
+          ref: ${{ github.event.inputs.ref }}
+
+      - name: Fetch PR by number
+        if: ${{ github.event.inputs.pr_number != 0 }}
+        run: |
+          PR_NUMBER=${{ github.event.inputs.pr_number }}
+          echo "pr number $PR_NUMBER"
+          git config --global --add safe.directory $(pwd)
+          git fetch origin pull/${PR_NUMBER}/head:pr-${PR_NUMBER}
+          git checkout pr-${PR_NUMBER}
+
+      - name: Print Env
+        run: |
+          echo "== pyenv =="
+          pyenv versions
+          echo "== python =="
+          python --version
+          echo "== nvcc =="
+          nvcc --version
+          echo "== torch =="
+          pip show torch
+
+          - name: Download wheel
+            continue-on-error: true
+            run: |
+              file_name=$(curl -s  -F "runid=${{ needs.check-vm.outputs.run_id }}" -F "repo=${{ env.repo }}" -F "ref=${{ env.ref }}" -F "fuzz=1" "http://${{ needs.check-vm.outputs.ip }}/gpu/whl/download")
+
+              if echo "$file_name" | grep -q "gptqmodel"; then
+                  mkdir dist || true
+                  cd dist
+                  curl -s -O  http://${{ needs.check-vm.outputs.ip }}/whl/${{ env.repo }}/${{ needs.check-vm.outputs.run_id }}/$file_name
+                  ls -ahl .
+                  sha256=$(sha256sum $file_name)
+                  echo "sha256=$sha256"
+                  echo "DOWNLOADED=1" >> $GITHUB_ENV
+              fi
+
+          - name: Download artifact
+            if: env.DOWNLOADED == '' && !cancelled()
+            uses: actions/download-artifact@v4
+            with:
+              name: dist
+              path: dist
+              run-id: ${{ needs.check-vm.outputs.run_id }}
+
+          - name: Install wheel
+            run: |
+              uv pip install auto_round optimum bitblas==0.0.1.dev13 parameterized uvicorn -i http://${{ needs.check-vm.outputs.ip }}/simple/ --trusted-host ${{ needs.check-vm.outputs.ip }}
+              uv pip install dist/*.whl
+              bash -c "$(curl -L http://$ZEN4_SERVER/scripts/compiler/init_env.sh)" @ 12.4 2.4.1 3.11
+              uv pip install transformers==4.38.2 numpy==1.26.4 -U -i http://${{ needs.check-vm.outputs.ip }}/simple/ --trusted-host ${{ needs.check-vm.outputs.ip }}
+
+          - name: Run tests
+            timeout-minutes: ${{ env.BITBLAS == '1' && 120 || 60 }}
+            if: ${{ (!github.event.inputs.test_names || contains(github.event.inputs.test_names, matrix.test_script)) && !cancelled() }}
+            run: pytest --durations=0 tests/${{ matrix.test_script }}.py || { echo "ERROR=1" >> $GITHUB_ENV; exit 1; }
+
+          - name: Release GPU
+            if: always()
+            run: curl -X GET "http://${{ env.GPU_IP }}/gpu/release?id=${{ github.run_id }}&gpu=${{ env.CUDA_VISIBLE_DEVICES }}&timestamp=${{ env.STEP_TIMESTAMP }}"
 
   torch2_5:
     needs:
